dist: trusty
language: go

addons:
  postgresql: "9.6"

go:
  - 1.9.x

matrix:
  allow_failures:
    - go: 1.9.x

notifications:
  email:
    - derkan@gmail.com

before_install:
  - psql -U postgres -c "CREATE ROLE bench LOGIN PASSWORD 'pass' VALID UNTIL 'infinity';"
  - psql -U postgres -c "CREATE DATABASE benchdb WITH OWNER = bench;"

install:
  - go get -u github.com/golang/dep/...
  - dep ensure